# Site Settings
baseurl: ""
url : "https://rlarmfo.github.io"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/img1.jpg
    username : 양현주
    description : 현주의 블로그에 오신걸 환영합니다
    experience :
      - start : 2020-03-01
        end : 2024-02-01
        experience : 제주대학교, 컴퓨터교육과 재학중
    skills : 
      - skill : 파이썬 & C언어 & 자바
        value : 85  # Percent value
        
  # Icons
  icons :
    email: "kimgr0504@gmail.com"
    linkedin:  # Full URL 
    github: rlarmfo
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
